# baseURL
@baseURL = http://localhost:8000

###
# Find All Users
GET {{ baseURL }}/products

###
# Create User
POST {{ baseURL }}/products
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Modify User By Id
PUT {{ baseURL }}/products/
Content-Type: application/json

{
    "productId": "88888",
    "price": "30"
}

###

